spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/woveny
    username: postgres
    password: 12345
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
#docker run --name pg-docker -e POSTGRES_PASSWORD=12345 -e POSTGRES_USER= root -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres
#ui docker run  --name admin-portal-db -e POSTGRES_PASSWORD=123qwe  -e POSTGRES_USER= root -d -p 5441:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres

woveny:
  etsy:
    rug:
      username: wovenyhome@gmail.com
      password: boyabat57
    pillow:
      username: hetyemez@yahoo.com
      password: etyemez57
  chairish:
    rug:
      username: wovenyrugs@gmail.com
      password: boyabat57
    pillow:
      username: hetyemez@yahoo.com
      password: etyemez57